version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  reviewers:
  - westonruter
  labels:
  - dependencies
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  reviewers:
  - westonruter
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.5.0
    - 31.6.1
    - 32.0.2
    - 32.0.3
    - 32.1.1
    - 32.3.1
    - 32.3.2
  - dependency-name: "@wordpress/eslint-plugin"
    versions:
    - 9.0.0
    - 9.0.2
    - 9.0.3
  - dependency-name: "@wordpress/plugins"
    versions:
    - 2.24.3
    - 2.24.4
    - 2.25.1
    - 2.25.2
  - dependency-name: "@wordpress/scripts"
    versions:
    - 13.0.2
    - 14.1.0
    - 14.1.1
  - dependency-name: workbox-cli
    versions:
    - 6.0.2
    - 6.1.0
    - 6.1.1
