# Tell Travis CI we're using PHP
language: php

# Newer versions like trusty don't have PHP 5.2 or 5.3
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin
    - $HOME/deployment-targets

install:
  - nvm install 6 && nvm use 6
  - npm install
  - npm run build
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

jobs:
  include:
    - stage: test
      php: "7.3"
      env: WP_VERSION=trunk
    - php: "7.2"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "5.6"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "5.6"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "7.1"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "7.0"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
