version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "westonruter"
    default_labels:
      - "dependencies"
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "westonruter"
    default_labels:
      - "dependencies"
